#Template from: https://github.com/ThreeDeeJay/GitHub-Actions-build-templates/blob/main/Windows-MSBuild.yml
name: Build

env:
  Branch: ${{github.ref_name}}
  Platform: x64
  Configuration: Release
  Artifacts: x64/Release/
  Solution: ${{github.event.repository.name}}.sln # .
  Executable: ${{github.event.repository.name}}.exe # *
  DXSDK_DIR: C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\

on:
  push:
    Branches: $Branch
  pull_request:
    Branches: $Branch
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    steps:

    - name: Clone repo and submodules
      run: git clone --recurse-submodules https://github.com/${{github.repository}}.git . --branch ${{env.Branch}}

    - name: Get current date, commit hash and count
      run: |
        echo "CommitDate=$(git show -s --date=format:'%Y-%m-%d' --format=%cd)" >> $env:GITHUB_ENV
        echo "CommitHash=$(git rev-parse HEAD)" >> $env:GITHUB_ENV
        echo "CommitHashShort=$(git rev-parse --short=7 HEAD)" >> $env:GITHUB_ENV
        echo "CommitCount=$(git rev-list --count HEAD)" >> $env:GITHUB_ENV

    - name: Cache DirectX SDK
      id: DXSDK_Jun10
      uses: actions/cache@v4
      with:
        path: ${{env.DXSDK_DIR}}
        key: DXSDK_Jun10
    - name: Install DirectX SDK
      if: steps.DXSDK_Jun10.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        Invoke-WebRequest -Method Get -Uri https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -OutFile DXSDK_Jun10.exe -UseBasicParsing
        Start-Process -Wait ./DXSDK_Jun10.exe -ArgumentList "/U"
    - name: Set DXSDK_DIR
      run: echo "DXSDK_DIR=C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)\" >> $env:GITHUB_ENV

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore "${{env.Solution}}"

    - name: Build
      run: msbuild /m "${{env.Solution}}" /p:Configuration="${{env.Configuration}}" #/p:Platform="${{env.Platform}}" /p:IncludePath="C:\Path\to\Include" /p:LibPath="C:\Path\to\Lib" /p:AdditionalIncludePaths="C:\Path\to\external\include" /p:AdditionalLibraryDirectories="C:\Path\to\external\lib" /p:LanguageStandard="stdcpp17"

    - name: List files
      run: ls -R

    - name: Upload Installer Artifact to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: "${{github.event.repository.name}}_r${{env.CommitCount}}@${{env.CommitHashShort}}"
        path: "${{github.workspace}}/${{env.Artifacts}}"

    - name: Compress artifacts
      uses: vimtor/action-zip@v1.1
      with:
        files: '${{env.Artifacts}}'
        dest: "build/${{github.event.repository.name}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"

    - name: Purge tag - latest
      run: |
        gh release delete latest --cleanup-tag --yes || true

    - name: Release - latest
      run: |
        gh release create latest --target ${{env.CommitHash}} --generate-notes --latest=true --title "[${{env.CommitDate}}] ${{github.event.repository.name}} r${{env.CommitCount}}@${{env.CommitHashShort}}" 
        gh release upload latest --clobber "build/${{github.event.repository.name}}_r${{env.CommitCount}}@${{env.CommitHashShort}}.zip"
